essential_question1: "어르신의 성함과 성별, 생년월일을 알려 주세요."
essential_question2: "어르신의 주소를 자세히 알려 주세요."
essential_question3: "어르신의 경력 사항을 알려 주세요."
essential_question4: "어르신께서 현재 앓고 계신 질환이나 불편하신 점이 있으시다면 말씀해 주세요. \
                      건강에 부담이 될 수 있는 업무는 피하도록 도와드리고 싶습니다."
essential_question5: "언제부터 근무가 가능하신지 알려 주세요.
                      근무 가능일과 시간대를 말씀해 주시면 좋습니다."