validation_question1: "답변이 질문과 관련이 있는지만 확인해주세요. \
                       완벽하지 않아도 질문 주제와 관련된 내용이 포함되어 있으면 유효합니다. \
                       예: '건강합니다'도 건강상태에 대한 유효한 답변입니다. \
                       누락된 정보가 있다면 10단어 이내로 간단히 설명해주세요."
